// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Aaron K. Clark
"use strict";

/**
 * report-pdf.js — render reports to a printable PDF (#433), export parity
 * beyond CSV. Currently the revenue summary.
 *
 * `pdfkit` is required lazily (only on the PDF path), matching
 * invoice-pdf.js. Input is a plain data object so this stays decoupled
 * from Sequelize and unit-testable. Amounts format through money.js so
 * printed figures match the stored NUMERIC exactly.
 */

const money = require('./money.js');

const SYMBOLS = { USD: '$', CAD: '$', AUD: '$', NZD: '$', EUR: '€', GBP: '£', JPY: '¥', INR: '₹' };
function fmtMoney(n, currency) {
    if (n == null) return '—';
    const code = typeof currency === 'string' && /^[A-Za-z]{3}$/.test(currency) ? currency.toUpperCase() : 'USD';
    const sym = SYMBOLS[code];
    return sym ? sym + money.toFixedString(n) : code + ' ' + money.toFixedString(n);
}

/** Draw a simple table; returns the y after the last row. Paginates at the page foot. */
function drawTable(doc, y, headers, rows, cols) {
    doc.fontSize(9).font('Helvetica-Bold').fillColor('#000');
    headers.forEach((h, i) => doc.text(h, cols[i].x, y, { width: cols[i].w, align: cols[i].align || 'left' }));
    y += 13;
    doc.moveTo(50, y).lineTo(545, y).stroke();
    y += 6;
    doc.fontSize(9).font('Helvetica');
    if (rows.length === 0) {
        doc.fillColor('#666').text('No data for this range.', 50, y);
        return y + 16;
    }
    for (const r of rows) {
        if (y > 770) { doc.addPage(); y = 50; }
        r.forEach((cell, i) => doc.text(String(cell), cols[i].x, y, { width: cols[i].w, align: cols[i].align || 'left' }));
        y += 14;
    }
    return y;
}

function drawRevenue(doc, data) {
    const company = data.company || {};
    const totals = data.totals || {};
    const byCustomer = Array.isArray(data.byCustomer) ? data.byCustomer : [];
    const byPeriod = Array.isArray(data.byPeriod) ? data.byPeriod : [];
    const m = (n) => fmtMoney(n, data.currency);

    // ---- Header ----
    doc.fillColor('#000').fontSize(18).font('Helvetica-Bold').text(company.name || 'Company', 50, 50);
    doc.fontSize(15).font('Helvetica-Bold').text(data.title || 'Revenue Summary', 50, 74);
    const subParts = [];
    if (data.range && data.range.from) subParts.push(`From ${data.range.from}`);
    if (data.range && data.range.to) subParts.push(`To ${data.range.to}`);
    const sub = [subParts.join('  '), data.generatedAt ? `Generated ${data.generatedAt}` : null].filter(Boolean).join('    ·    ');
    if (sub) doc.fontSize(9).font('Helvetica').fillColor('#666').text(sub, 50, 96);
    doc.fillColor('#000').moveTo(50, 112).lineTo(545, 112).stroke();

    // ---- Totals ----
    let y = 126;
    doc.fontSize(10).font('Helvetica-Bold').text('TOTALS', 50, y);
    y += 16;
    const totalRow = (label, value, bold) => {
        doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(10);
        doc.text(label, 50, y, { width: 250 });
        doc.text(value, 350, y, { align: 'right', width: 195 });
        y += 15;
    };
    totalRow('Invoices', String(totals.invoiceCount != null ? totals.invoiceCount : 0));
    totalRow('Revenue (invoiced)', m(totals.revenue));
    totalRow('Collected', m(totals.collected));
    totalRow('Outstanding', m(totals.outstanding), true);

    // ---- By customer ----
    y += 14;
    doc.fontSize(10).font('Helvetica-Bold').text('BY CUSTOMER', 50, y);
    y += 16;
    y = drawTable(doc, y,
        ['Customer', 'Inv', 'Revenue', 'Collected', 'Outstanding'],
        byCustomer.map((c) => [c.custName || '—', c.invoiceCount || 0, m(c.revenue), m(c.collected), m(c.outstanding)]),
        [
            { x: 50, w: 195, align: 'left' },
            { x: 250, w: 40, align: 'right' },
            { x: 300, w: 80, align: 'right' },
            { x: 385, w: 80, align: 'right' },
            { x: 470, w: 75, align: 'right' },
        ],
    );

    // ---- By month ----
    y += 14;
    if (y > 740) { doc.addPage(); y = 50; }
    doc.fontSize(10).font('Helvetica-Bold').fillColor('#000').text('BY MONTH', 50, y);
    y += 16;
    y = drawTable(doc, y,
        ['Period', 'Inv', 'Revenue', 'Collected'],
        byPeriod.map((g) => [g.period || '—', g.invoiceCount || 0, m(g.revenue), m(g.collected)]),
        [
            { x: 50, w: 120, align: 'left' },
            { x: 250, w: 40, align: 'right' },
            { x: 300, w: 100, align: 'right' },
            { x: 405, w: 100, align: 'right' },
        ],
    );

    // ---- Footer ----
    doc.fontSize(8).font('Helvetica').fillColor('#666')
        .text(company.footer || 'Generated by TimeTrackerAPI.', 50, 800, { align: 'center', width: 495 });
}

/**
 * Render the revenue report `data` to a PDF Buffer.
 * @returns {Promise<Buffer>}
 */
function renderRevenuePdf(data) {
    const PDFDocument = require('pdfkit');
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ size: 'A4', margin: 50 });
        const chunks = [];
        doc.on('data', (c) => chunks.push(c));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);
        try {
            drawRevenue(doc, data || {});
            doc.end();
        } catch (err) {
            reject(err);
        }
    });
}

module.exports = { renderRevenuePdf };
